# Generated by Django 5.1.1 on 2024-10-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingtips',
            name='category',
        ),
    ]
