# Generated by Django 5.2.5 on 2025-08-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
    ]
