# Generated by Django 5.1.1 on 2024-10-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_cookingtips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingtips',
            name='created_at',
        ),
    ]
