# Generated by Django 5.2.5 on 2025-08-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favourites_added_on_remove_favourites_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='recipe_name',
            new_name='recipe_title',
        ),
    ]
