# Generated by Django 5.1.1 on 2024-10-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_remove_cookingtips_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookingTips',
        ),
    ]
