# Generated by Django 5.1.1 on 2024-11-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_delete_cookingtips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='added_on',
        ),
    ]
