# Generated by Django 5.1.1 on 2024-11-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_remove_favourites_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
    ]
