# Generated by Django 5.2.5 on 2025-08-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edamam_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.TextField()),
                ('servings', models.IntegerField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuisine_type', models.JSONField(default=list)),
                ('is_homepage_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
