# Generated by Django 5.2.5 on 2025-08-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='edamam_id',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='recipe_title',
        ),
    ]
